### ISSUE TITLE
Missing doc on exe_command

### ISSUE THREAD

**Issue by tsgouvea** [flatironinstitute/mountainlab-js#16]
Documentation on [how to create custom processor libraries](https://github.com/flatironinstitute/mountainlab-js/blob/master/docs/creating_custom_processor_libraries.md) is truncated at the section "Formatting the exe command."
Examples are not sufficiently clarifying, specially for processors written in different languages.

**Comment by alexmorley** [comment]
Having a look at this now at #17 

Out of interest what is your go-to language? It'd be cool to create ml_identity packages for lot's of languages so it's easy for people to work out what's going on (especially as the python one we have at the moment is a rather special case as mltools is doing a bit of magic there).

**Comment by alexmorley** [comment]
Oh just seen you have a mp_minim package. Can we rename it ml_identity_matlab or ml_identity_octave? 

Am happy to help go through this so we can work out how to make it clear for everyone.

**Comment by alexmorley** [comment]
https://github.com/tsgouvea/mp_minim

**Comment by tsgouvea** [comment]
@alexmorley that'd be great!
I've [renamed it](https://github.com/tsgouvea/ml_identity_matlab).

**Comment by tsgouvea** [comment]
I have [ml_identity_matlab](https://github.com/tsgouvea/ml_identity_matlab) working - thanks for the help.
Perhaps it could be added to documentation alongside your Python template.

**Comment by alexmorley** [comment]
Finally done! See #21
