### ISSUE TITLE
ms4alg error with intermediate files

### ISSUE THREAD

**Issue by izouridis** [flatironinstitute/mountainlab-js#25]
Hello mountainlab-js developers,

I'm trying to use ms4alg with my data and I get this error: 
KeyError: "Unable to open object (file read failed: time = Tue Jun 19 16:04:17 2018\n, filename = '/media/C/Projects/SPIKE_SORT/temp/tempdir_a072851555_xIrCyD/timeseries.hdf5', file descriptor = 4, errno = 22, error message = 'Invalid argument', buf = 0x2f0a168, total read size = 544, bytes this sub-read = 544, bytes actually read = 18446744073709551615, offset = 5405935000)"

Here is the full output: https://pastebin.com/LP8qf5wC

Best,
Ioannis

**Comment by alexmorley** [comment]
Hey, could you just confirm that this happens every time you sort on this dataset? And/or on other datasets?

**Comment by izouridis** [comment]
This happens with most of my datasets (11/12). There is one dataset that seems to work fine and it happens to be the smallest one.

**Comment by alexmorley** [comment]
could you let us know how much RAM you have. The size of the dataset that doesn't work. And how much space you have in `/media/C/`?

**Comment by izouridis** [comment]
RAM allocated to the VM: 106.466 GB.
Free space in /media/C: >640 GB.
Size of dataset (raw.mda) that doesn't work: 39.9 GB
Size of intermediate file: 19.7 GB

**Comment by izouridis** [comment]
@magland this problem has been fixed. I close this issue. Thank you.
