### ISSUE TITLE
example 002 could not connect ot lari server

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/mountainlab-js#5]
Hi Jeremy -
the example 001 sort and view example bash scripts work.
However, 002 doesn't. I haven't started a local server since it's not clear I had to - do I?
Assuming I do,  ml-lari-start
isn't found even if I'm in the lm-env virtualenv.
Thanks, Alex

**Comment by magland** [comment]
Did you add mountainlab-js/bin to your path? In that case, ml-lari-start should be available command. Is it not?
You are right that I need to add that to the documentation.

Running the lari server is an extra step... but there are a lot of advantages of doing it. Especially when processing a large number of jobs. Or running things from the web.

**Comment by ahbarnett** [comment]
Thanks - works! Rest of example 002 is really cool.

I'm having some PATH issues - basically I keep needing to add things to PATH once
in the "source ~/ml-env/bin/activate" virtualenv.
Eg: mltools,    ev-*    ml-*  

But if I keep adding things to PATH by hand (I can't add them to ~/.bashrc since sourcing that seems to wipe out the virtualenv...) things work. 

I really like the new comparison table & metrics viewers - we can augment this to be more graphical/sortable.

Will leave you to close issue when fix docs.. A

**Comment by magland** [comment]
I am really not sure why your path is getting wiped out. Can you post that portion of your .bashrc?

**Comment by alexmorley** [comment]
Is this fixed?

**Comment by magland** [comment]
I will close and then follow up with Alex. The title of this issue no longer applies since we don't need to run lari server any more for the example.
