### ISSUE TITLE
Both Moutainview and qt-mountainview fail to create prv file

### ISSUE THREAD

**Issue by fullerene12** [flatironinstitute/mountainlab-js#72]
It seems like the flatiron kbucket server failed. Is there a way to easily create and resolve .prv files locally? Thank you!

The prv resolve failure is across multiple computers in multiple labs in different universities. Mountainview was working a few days ago on all these computers. Nothing has been changed and we are trying to open the same data sets that were successfully loaded before.

Browser query of https://kbucket.flatironinstitute.org/ yields a page titled ERROR, with the message: Cannot GET /

After typing in:

> mountainview --pre=pre.mda --firings=firings.curated.mda --samplerate=30000 --cluster_metrics=metrics_curated.json

I get the following output:

> Setting up object registry...
> Parsing command-line parameters...
> Creating MVContext...
> Setting up context...
> {
>     "original_checksum": "1febe49759c57f5855a71deb15b52f8bb7bf2ab9",
>     "original_fcs": "head1000-566e4080e17c76e4f3d9b48548e64b1cae6a25fe",
>     "original_path": "/tmp/mountainlab-tmp/output_a130ed5fda9cb7323699a3c1efe05dff5c28b4fa_timeseries_out.mda",
>     "original_size": 1219657748,
>     "prv_version": "0.11"
> }
> 
> Unable to load DiskReadMda32 because .prv file could not be resolved.
> {
>     "original_checksum": "1febe49759c57f5855a71deb15b52f8bb7bf2ab9",
>     "original_fcs": "head1000-566e4080e17c76e4f3d9b48548e64b1cae6a25fe",
>     "original_path": "/tmp/mountainlab-tmp/output_a130ed5fda9cb7323699a3c1efe05dff5c28b4fa_timeseries_out.mda",
>     "original_size": 1219657748,
>     "prv_version": "0.11"
> }
> 
> Unable to load DiskReadMda32 because .prv file could not be resolved.
> Creating prv object for: firings.curated.mda
> Unable to construct DiskReadMda32 from prv_object. Unable to resolve. Original path =  "/tmp/mountainlab-tmp/output_a130ed5fda9cb7323699a3c1efe05dff5c28b4fa_timeseries_out.mda"
> Setting up main window...
> Adding controls to main window...
> Opening initial views...
> Starting event loop...
> 2018-10-02:23-18-12-544	mproc.main	warning	"Unable to find processor: ms3.mv_compute_templates"
> ":::: Failed to open DiskReadMda32 file: /tmp/mountainlab/tmp_long_term/ed89dc3cf572b8dfdbd13c92241ddfbc3750e9db_templates_out.tmp"
> "File does not exist: /tmp/mountainlab/tmp_long_term/ed89dc3cf572b8dfdbd13c92241ddfbc3750e9db_templates_out.tmp"
> Unable to read chunk of templates in cluster detail view
> 2018-10-02:23-18-25-272	mproc.main	warning	"Unable to find processor: ms3.mv_compute_amplitudes"
> ":::: Failed to open diskreadmda file: /tmp/mountainlab/tmp_long_term/31c39b97276fbca5cdcb82b2519b1630e16b47db_firings_out.tmp"
> "File does not exist: /tmp/mountainlab/tmp_long_term/31c39b97276fbca5cdcb82b2519b1630e16b47db_firings_out.tmp"
>

**Comment by alexmorley** [comment]
Hey, @fullerene12 . Where are the datasets you are trying to load physically located? It looks to me like the file the .prv was resolving to has been deleted from the /tmp directory. So you might need to re-generate it.

**Comment by fullerene12** [comment]
Thanks! It is physically located in my home filesystem, but it seems like the last time I used qt-mountainview it was copying files into /tmp, and /tmp was cleaned. When I re-generated the prv files, qt-mountainview works again, though the error message is still the same in mountainview.

**Comment by tjd2002** [comment]
A user in our lab had (@hrjoo) had a similar issue. She could view firing events and spike spray once, but then not when running qt-mountainview a second time.
